### ISSUE TITLE
can't no execute bag_convert

### ISSUE THREAD

**Issue by Matrix-Hearts** [daohu527/bag_convert#1]
Sorry, this is my first time raising an issue. I just entered the title and pressed Enter to submit the issue.The following is my problem description.

### Description:
After I installed bag_convert, I could not run "bag_convert" in the terminal, and the terminal displayed` bag_convert: command not found`. So, I added the path `export PATH="$PATH:$HOME/.local/bin"`.
At this time another error occurred,The following is the terminal prompt：
```
Traceback (most recent call last):
  File "/home/usr/.local/bin/bag_convert", line 5, in <module>
    from bag_convert.main import main
  File "/home/usr/.local/lib/python3.8/site-packages/bag_convert/main.py", line 23, in <module>
    import bag_convert.bag2record.bag2record as bag2record
  File "/home/usr/.local/lib/python3.8/site-packages/bag_convert/bag2record/bag2record.py", line 20, in <module>
    from cyber_record.record import Record
  File "/home/usr/.local/lib/python3.8/site-packages/cyber_record/record.py", line 24, in <module>
    from cyber_record.cyber.proto import record_pb2, proto_desc_pb2
  File "/home/usr/.local/lib/python3.8/site-packages/cyber_record/cyber/proto/record_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```
how can i solve this problem

**Comment by Matrix-Hearts** [comment]
Sorry, this is my first time raising an issue. I just entered the title and pressed Enter to submit the issue.The following is my problem description.
### System： Linux Ubuntu 20.04
### Description：
After I installed bag_convert, I could not run "bag_convert" in the terminal, and the terminal displayed `bag_convert: command not found`. So, I added the path `export PATH="$PATH:$HOME/.local/bin"`.
At this time another error occurred,The following is the terminal prompt：
```
Traceback (most recent call last):
  File "/home/usr/.local/bin/bag_convert", line 5, in <module>
    from bag_convert.main import main
  File "/home/usr/.local/lib/python3.8/site-packages/bag_convert/main.py", line 23, in <module>
    import bag_convert.bag2record.bag2record as bag2record
  File "/home/usr/.local/lib/python3.8/site-packages/bag_convert/bag2record/bag2record.py", line 20, in <module>
    from cyber_record.record import Record
  File "/home/usr/.local/lib/python3.8/site-packages/cyber_record/record.py", line 24, in <module>
    from cyber_record.cyber.proto import record_pb2, proto_desc_pb2
  File "/home/usr/.local/lib/python3.8/site-packages/cyber_record/cyber/proto/record_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```
how can i solve this problem

**Comment by daohu527** [comment]
This may be caused by the version of protobuf, you can try
```
pip3 install protobuf==3.19.4
```

**Comment by Matrix-Hearts** [comment]
Thank you very much for the answer.When I executed command `pip3 install protobuf==3.19.4`, the following problem occurred. So I uninstalled and reinstalled `bag_convert`, but the problem still exist.
```
Traceback (most recent call last):
  File "/home/usr/.local/bin/bag_convert", line 5, in <module>
    from bag_convert.main import main
  File "/home/usr/.local/lib/python3.8/site-packages/bag_convert/main.py", line 23, in <module>
    import bag_convert.bag2record.bag2record as bag2record
  File "/home/usr/.local/lib/python3.8/site-packages/bag_convert/bag2record/bag2record.py", line 21, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by daohu527** [comment]
fixed this, you can use
```
pip3 install tqdm
```
