### ISSUE TITLE
cant no execute

### ISSUE THREAD

**Issue by Neilyooo** [daohu527/bag_convert#2]
Linux Ubuntu 18.04 protobuf 3.19.4 python3.8
Description:
The following is the terminal prompt：chatgpt@chatgpt-MS-7B51:~/Downloads/apollo/bag_convert$ bag_convert -m=r2b -r=/media/chatgpt/FED8431CD842D297/Download/20240708_190030_C.record.00000 -b=/media/chatgpt/FED8431CD842D297/Download/apollo/00.bag
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
bag to record progress: 1it [00:00,  6.15it/s]Traceback (most recent call last):
  File "/home/chatgpt/.local/bin/bag_convert", line 8, in <module>
    sys.exit(main())
  File "/home/chatgpt/Downloads/apollo/bag_convert/bag_convert/main.py", line 59, in main
    record2bag.convert(record_file, bag_file)
  File "/home/chatgpt/Downloads/apollo/bag_convert/bag_convert/record2bag/record2bag.py", line 53, in convert
    msg = convert_msg(msg)
  File "/home/chatgpt/Downloads/apollo/bag_convert/bag_convert/record2bag/record2bag.py", line 38, in convert_msg
    return to_pointcloud(cyber_msg)
  File "/home/chatgpt/Downloads/apollo/bag_convert/bag_convert/record2bag/pointcloud2.py", line 30, in to_pointcloud
    for point_xyzit in cyber_pointcloud.point:
AttributeError: point
bag to record progress: 8it [00:00, 26.76it/s]
how can i solve this problem

**Comment by daohu527** [comment]
I have updated the record_msgs package, could you please try again?

The reason for this error is that the point attribute cannot be found, which seems a bit strange
